# Build and run test for every commit and all branches
# Push image only for master branches
# Deploy for master - stag and prod - prod


# jobs:
#   build:
#     docker:
#       - image: circleci/<language>:<version TAG>
#     steps:
#       - checkout
#       - run: <command>
#   test:
#     docker:
#       - image: circleci/<language>:<version TAG>
#     steps:
#       - checkout
#       - run: <command>
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test

ignore_protected_branches: &ignore_protected_branches
  filters:
    branches:
      ignore:
        - master
        - prod



version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker
      # - restore_cache:
      #     keys:
      #       - v1-{{ .Branch }}
      #     paths:
      #       - /caches/app.tar
      # - run:
      #     name: Load Docker image layer cache
      #     command: |
      #       set +o pipefail
      #       docker load -i /caches/app.tar | true
      - run:
          name: Install deps
          command: |
            export PATH=/root/google-cloud-sdk/bin:$PATH
            sh .circleci/install_deps.sh
            ./cli check
      # - save_cache:
      #     key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      #     paths:
      #       - /
      - run:
          name: Build images
          command: |
            export PATH=/root/google-cloud-sdk/bin:$PATH 
            ./cli build
      - run:
          name: Run tests
          command: |
            export PATH=/root/google-cloud-sdk/bin:$PATH 
            ./cli test
      - run:
          name: Push Docker images to GCP
          command: |
            export PATH=/root/google-cloud-sdk/bin:$PATH 
            ./cli push
      # - run:
      #     name: Save Docker image layer cache
      #     command: |
      #       mkdir -p /caches
      #       docker save -o /caches/app.tar app
      # - save_cache:
      #     key: v1-{{ .Branch }}-{{ epoch }}
      #     paths:
      #       - /caches/app.tar


workflows:
  version: 2
  ci_checks:
    jobs:
      - build:
          <<: *ignore_protected_branches
