apiVersion: v1            
kind: Service             
metadata:                 
  name: nginx   
spec:                     
  selector:               
    app: kubernetes-nginx
  ports: [{protocol: "TCP", targetPort: 80, port: 80, name: "http"}]
  type: LoadBalancer
